<a href="https://colab.research.google.com/github/Khalil032/Khalil2/blob/main/Homework5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Case Intro
Term deposits are a major source of income for a bank. A term deposit is a cash investment held at a financial institution. Your money is invested for an agreed rate of interest over a fixed amount of time, or term. The bank has various outreach plans to sell term deposits to their customers such as email marketing, advertisements, telephonic marketing, and digital marketing.

Telephonic marketing campaigns still remain one of the most effective way to reach out to people. However, they require huge investment as large call centers are hired to actually execute these campaigns. Hence, it is crucial to identify the customers most likely to convert beforehand so that they can be specifically targeted via call.

The data is related to direct marketing campaigns (phone calls) of a Portuguese banking institution. The classification goal is to predict if the client will subscribe to a term deposit (variable y).

Content
The data is related to the direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed by the customer or not. The data folder contains two datasets:-

Bank.csv: 45,211 rows and 18 columns ordered by date (from May 2008 to November 2010)

Detailed Column Descriptions
bank client data:

1 - age (numeric)

2 - job : type of job (categorical: "admin.","unknown","unemployed","management","housemaid","entrepreneur","student",
"blue-collar","self-employed","retired","technician","services")

3 - marital : marital status (categorical: "married","divorced","single"; note: "divorced" means divorced or widowed)

4 - education (categorical: "unknown","secondary","primary","tertiary")

5 - default: has credit in default? (binary: "yes","no")

6 - balance: average yearly balance, in euros (numeric)

7 - housing: has housing loan? (binary: "yes","no")

8 - loan: has personal loan? (binary: "yes","no")
# related with the last contact of the current campaign:
9 - contact: contact communication type (categorical: "unknown","telephone","cellular")
10 - day: last contact day of the month (numeric)

11 - month: last contact month of year (categorical: "jan", "feb", "mar", â€¦, "nov", "dec")

12 - duration: last contact duration, in seconds (numeric)

# other attributes:
13 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)

14 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric, -1 means client was not previously contacted)

15 - previous: number of contacts performed before this campaign and for this client (numeric)

16 - poutcome: outcome of the previous marketing campaign (categorical: "unknown","other","failure","success")

Output variable (desired target):

17 - y - has the client subscribed a term deposit? (binary: "yes","no")

Missing Attribute Values: None

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('https://raw.githubusercontent.com/ogut77/DataScience/main/data/Bank.csv',sep = ';')
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [2]:
print(df.shape)
df.info()
df.isnull().sum()

(45211, 17)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [3]:
#For object check the data 
for cn in df.columns:
  if(df[cn].dtype==object):
    print(df[cn].value_counts())

blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: job, dtype: int64
married     27214
single      12790
divorced     5207
Name: marital, dtype: int64
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: education, dtype: int64
no     44396
yes      815
Name: default, dtype: int64
yes    25130
no     20081
Name: housing, dtype: int64
no     37967
yes     7244
Name: loan, dtype: int64
cellular     29285
unknown      13020
telephone     2906
Name: contact, dtype: int64
may    13766
jul     6895
aug     6247
jun     5341
nov     3970
apr     2932
feb     2649
jan     1403
oct      738
sep      579
mar      477
dec      214
Name: month, dtype: int64
unknown    36959
failure     4901
other       1840
success     1511
Name: poutcome, dtype: int64
no     39922
yes     5289
Name: y, dtype: int64

In [4]:
def Encoder(df):
          from sklearn import preprocessing
          columnsToEncode = list(df.select_dtypes(include=['category','object']))
          le = preprocessing.LabelEncoder()
          for feature in columnsToEncode:
              try:
                  df[feature] = le.fit_transform(df[feature])
              except:
                  print('Error encoding '+feature)
          return df

In [5]:
df=Encoder(df)
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,4,1,2,0,2143,1,0,2,5,8,261,1,-1,0,3,0
1,44,9,2,1,0,29,1,0,2,5,8,151,1,-1,0,3,0
2,33,2,1,1,0,2,1,1,2,5,8,76,1,-1,0,3,0
3,47,1,1,3,0,1506,1,0,2,5,8,92,1,-1,0,3,0
4,33,11,2,3,0,1,0,0,2,5,8,198,1,-1,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,9,1,2,0,825,0,0,0,17,9,977,3,-1,0,3,1
45207,71,5,0,0,0,1729,0,0,0,17,9,456,2,-1,0,3,1
45208,72,5,1,1,0,5715,0,0,0,17,9,1127,5,184,3,2,1
45209,57,1,1,1,0,668,0,0,1,17,9,508,4,-1,0,3,0
45210,37,2,1,1,0,2971,0,0,0,17,9,361,2,188,11,1,0

In [6]:
y = df['y'] #Output
X = df.drop('y',axis=1)
X

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
0,58,4,1,2,0,2143,1,0,2,5,8,261,1,-1,0,3
1,44,9,2,1,0,29,1,0,2,5,8,151,1,-1,0,3
2,33,2,1,1,0,2,1,1,2,5,8,76,1,-1,0,3
3,47,1,1,3,0,1506,1,0,2,5,8,92,1,-1,0,3
4,33,11,2,3,0,1,0,0,2,5,8,198,1,-1,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,9,1,2,0,825,0,0,0,17,9,977,3,-1,0,3
45207,71,5,0,0,0,1729,0,0,0,17,9,456,2,-1,0,3
45208,72,5,1,1,0,5715,0,0,0,17,9,1127,5,184,3,2
45209,57,1,1,1,0,668,0,0,1,17,9,508,4,-1,0,3
45210,37,2,1,1,0,2971,0,0,0,17,9,361,2,188,11,1

In [7]:
from sklearn.model_selection import  train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=17)

 


Q1)Using  Random Forest,XGBoost, Light GBM and Gradient Boosting Classifier with default parameters (no parameter specifications except random_state) calculate Accuracy on Test data. Which method gives the best accuracy on test data

In [9]:
#Question1
#Random Forest 
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(random_state=17 )
forest.fit(X_train, y_train)

# make predictions for test data

forest_pred = forest.predict(X_test)
print(accuracy_score(y_test, forest_pred) )

# XGBoost
from xgboost import XGBClassifier
model = XGBClassifier(random_state=17)
model.fit(X_train, y_train)
# make predictions for test data
xgb_pred = model.predict(X_test)
print(accuracy_score(y_test, xgb_pred))
#Light GBM
import lightgbm as lgb
lgb_model = lgb.LGBMClassifier(random_state=17)
lgb_model.fit(X_train, y_train)
# make predictions for test data
print(accuracy_score(y_test, lgb_model.predict(X_test)))
#Gradient Boosting
from sklearn.ensemble import GradientBoostingClassifier
gbm_model = GradientBoostingClassifier(random_state=17)
gbm_model.fit(X_train, y_train)
print(accuracy_score(y_test, gbm_model.predict(X_test)))

0.9025037600636999
0.90020348580023
0.9044501459789437
0.9018844554543042

Q2) Using optuna hyperparmeter optimization technique and 100 trial

 a)find best methods with  parameters  using Cross validation (CV=3) technique for the range of   parameters below. What are the best parameters for the method with highest cross validation accuracy?

"max_depth": range(2, 16), "max_features": range(2, 16)

 b)Evaluate the performance of the  method with highest cross validation accuracy on test data.What is the accuracy value?

In [11]:
#Question2
!pip install optuna

Collecting optuna
  Downloading optuna-2.10.0-py3-none-any.whl (308 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 308 kB 5.3 MB/s
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from optuna) (1.21.5)
Collecting cliff
  Downloading cliff-3.10.1-py3-none-any.whl (81 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 81 kB 9.3 MB/s
Requirement already satisfied: scipy!=1.4.0 in /usr/local/lib/python3.7/dist-packages (from optuna) (1.4.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.7/dist-packages (from optuna) (3.13)
Collecting alembic
  Downloading alembic-1.7.7-py3-none-any.whl (210 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 210 kB 60.5 MB/s
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from optuna) (21.3)
Requirement already satisfied: sqlalchemy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from optuna) (1.4.32)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from optuna) (4.63.0)
Collecting colorlog
  Downloading colorlog-6.6.0-py2.py3-none-any.whl (11 kB)
Collecting cmaes>=0.8.2
  Downloading cmaes-0.8.2-py3-none-any.whl (15 kB)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->optuna) (3.0.7)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy>=1.1.0->optuna) (1.1.2)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from sqlalchemy>=1.1.0->optuna) (4.11.3)
Collecting Mako
  Downloading Mako-1.2.0-py3-none-any.whl (78 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 78 kB 7.8 MB/s
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.7/dist-packages (from alembic->optuna) (5.4.0)
Collecting autopage>=0.4.0
  Downloading autopage-0.5.0-py3-none-any.whl (29 kB)
Collecting cmd2>=1.0.0
  Downloading cmd2-2.4.0-py3-none-any.whl (150 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 150 kB 55.6 MB/s
Collecting pbr!=2.1.0,>=2.0.0
  Downloading pbr-5.8.1-py2.py3-none-any.whl (113 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 113 kB 53.8 MB/s
Collecting stevedore>=2.0.1
  Downloading stevedore-3.5.0-py3-none-any.whl (49 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 49 kB 6.2 MB/s
Requirement already satisfied: PrettyTable>=0.7.2 in /usr/local/lib/python3.7/dist-packages (from cliff->optuna) (3.2.0)
Collecting pyperclip>=1.6
  Downloading pyperclip-1.8.2.tar.gz (20 kB)
Requirement already satisfied: attrs>=16.3.0 in /usr/local/lib/python3.7/dist-packages (from cmd2>=1.0.0->cliff->optuna) (21.4.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from cmd2>=1.0.0->cliff->optuna) (3.10.0.2)
Requirement already satisfied: wcwidth>=0.1.7 in /usr/local/lib/python3.7/dist-packages (from cmd2>=1.0.0->cliff->optuna) (0.2.5)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy>=1.1.0->optuna) (3.7.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.7/dist-packages (from Mako->alembic->optuna) (2.0.1)
Building wheels for collected packages: pyperclip
  Building wheel for pyperclip (setup.py) ... done
  Created wheel for pyperclip: filename=pyperclip-1.8.2-py3-none-any.whl size=11137 sha256=7d6182c7e03face48ffb0e9c4ab9770375f69358329ab8109196129582fb381f
  Stored in directory: /root/.cache/pip/wheels/9f/18/84/8f69f8b08169c7bae2dde6bd7daf0c19fca8c8e500ee620a28
Successfully built pyperclip
Installing collected packages: pyperclip, pbr, stevedore, Mako, cmd2, autopage, colorlog, cmaes, cliff, alembic, optuna
Successfully installed Mako-1.2.0 alembic-1.7.7 autopage-0.5.0 cliff-3.10.1 cmaes-0.8.2 cmd2-2.4.0 colorlog-6.6.0 optuna-2.10.0 pbr-5.8.1 pyperclip-1.8.2 stevedore-3.5.0

In [13]:
import optuna

import sklearn.datasets
import sklearn.ensemble
import sklearn.model_selection
import sklearn.svm

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=17)
# FYI: Objective functions can take additional arguments
# (https://optuna.readthedocs.io/en/stable/faq.html#objective-func-additional-args).
def objective(trial):
    x, y = X_train,y_train

    regressor_name = trial.suggest_categorical("regressor", ["GradientBoosting", "XGBoost","LightGBM","RandomForest"])
    if regressor_name == "GradientBoosting":
         max_depth = trial.suggest_int("max_depth",2,16)
         max_features = trial.suggest_int("max_features",2,16)
         regressor_obj = sklearn.ensemble.GradientBoostingRegressor(random_state=17,  max_depth=max_depth, max_features=max_features )
    elif regressor_name == "XGBoost":
         from xgboost import XGBRegressor
         max_depth = trial.suggest_int("max_depth",2,16)
         max_features = trial.suggest_int("max_features",2,16)
         regressor_obj = XGBRegressor(random_state=17,  max_depth=max_depth, max_features=max_features )
        
         

    elif regressor_name == "LightGBM":
         import lightgbm as lgb
         max_depth = trial.suggest_int("max_depth",2,16)
         max_features = trial.suggest_int("max_features",2,16)
         regressor_obj = lgb.LGBMRegressor(random_state=17,  max_depth=max_depth, max_features=max_features )
        
       
   
    else:
         max_depth = trial.suggest_int("max_depth",2,16)
         max_features = trial.suggest_int("max_features",2,16)
         regressor_obj = sklearn.ensemble.RandomForestRegressor(random_state=17,  max_depth=max_depth, max_features=max_features )
    r2=sklearn.model_selection.cross_val_score(regressor_obj, x, y, n_jobs=-1, cv=3).mean()
   
    return r2


if __name__ == "__main__":
    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=100)
    print(study.best_trial)

[I 2022-03-27 18:12:14,456] A new study created in memory with name: no-name-fbcfeea7-b027-4984-93e2-70c3e7a52afd
[I 2022-03-27 18:12:27,770] Trial 0 finished with value: 0.3623717035581544 and parameters: {'regressor': 'RandomForest', 'max_depth': 12, 'max_features': 9}. Best is trial 0 with value: 0.3623717035581544.
[I 2022-03-27 18:12:28,810] Trial 1 finished with value: 0.3285509525098687 and parameters: {'regressor': 'LightGBM', 'max_depth': 2, 'max_features': 12}. Best is trial 0 with value: 0.3623717035581544.
[I 2022-03-27 18:12:48,085] Trial 2 finished with value: 0.3715855529020655 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 7, 'max_features': 10}. Best is trial 2 with value: 0.3715855529020655.
[I 2022-03-27 18:12:53,561] Trial 3 finished with value: 0.37718251871845015 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 3 with value: 0.37718251871845015.
[I 2022-03-27 18:12:59,206] Trial 4 finished with value: 0.37531265338631686 and parameters: {'regressor': 'XGBoost', 'max_depth': 5, 'max_features': 6}. Best is trial 3 with value: 0.37718251871845015.
[I 2022-03-27 18:13:03,620] Trial 5 finished with value: 0.3679084045606677 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 3 with value: 0.37718251871845015.
[I 2022-03-27 18:13:04,403] Trial 6 finished with value: 0.359339894831263 and parameters: {'regressor': 'LightGBM', 'max_depth': 3, 'max_features': 7}. Best is trial 3 with value: 0.37718251871845015.
[I 2022-03-27 18:13:11,430] Trial 7 finished with value: 0.3763815414974146 and parameters: {'regressor': 'XGBoost', 'max_depth': 6, 'max_features': 4}. Best is trial 3 with value: 0.37718251871845015.
[I 2022-03-27 18:13:24,897] Trial 8 finished with value: 0.34157984387705786 and parameters: {'regressor': 'XGBoost', 'max_depth': 10, 'max_features': 3}. Best is trial 3 with value: 0.37718251871845015.
[I 2022-03-27 18:13:39,663] Trial 9 finished with value: 0.35842386675149945 and parameters: {'regressor': 'RandomForest', 'max_depth': 13, 'max_features': 13}. Best is trial 3 with value: 0.37718251871845015.
[I 2022-03-27 18:14:00,206] Trial 10 finished with value: 0.34522824354768256 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 9, 'max_features': 16}. Best is trial 3 with value: 0.37718251871845015.
[I 2022-03-27 18:14:08,540] Trial 11 finished with value: 0.3722141260506455 and parameters: {'regressor': 'XGBoost', 'max_depth': 7, 'max_features': 2}. Best is trial 3 with value: 0.37718251871845015.
[I 2022-03-27 18:14:36,985] Trial 12 finished with value: 0.2764069659439999 and parameters: {'regressor': 'XGBoost', 'max_depth': 16, 'max_features': 4}. Best is trial 3 with value: 0.37718251871845015.
[I 2022-03-27 18:14:41,817] Trial 13 finished with value: 0.37563357502206457 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 5}. Best is trial 3 with value: 0.37718251871845015.
[I 2022-03-27 18:14:53,815] Trial 14 finished with value: 0.36086073351455566 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 9, 'max_features': 9}. Best is trial 3 with value: 0.37718251871845015.
[I 2022-03-27 18:14:59,435] Trial 15 finished with value: 0.37531265338631686 and parameters: {'regressor': 'XGBoost', 'max_depth': 5, 'max_features': 5}. Best is trial 3 with value: 0.37718251871845015.
[I 2022-03-27 18:15:00,577] Trial 16 finished with value: 0.11261038241895016 and parameters: {'regressor': 'RandomForest', 'max_depth': 2, 'max_features': 2}. Best is trial 3 with value: 0.37718251871845015.
[I 2022-03-27 18:15:01,717] Trial 17 finished with value: 0.38780396438906567 and parameters: {'regressor': 'LightGBM', 'max_depth': 8, 'max_features': 7}. Best is trial 17 with value: 0.38780396438906567.
[I 2022-03-27 18:15:02,826] Trial 18 finished with value: 0.3882812159412718 and parameters: {'regressor': 'LightGBM', 'max_depth': 12, 'max_features': 10}. Best is trial 18 with value: 0.3882812159412718.
[I 2022-03-27 18:15:03,935] Trial 19 finished with value: 0.3882812159412718 and parameters: {'regressor': 'LightGBM', 'max_depth': 12, 'max_features': 10}. Best is trial 18 with value: 0.3882812159412718.
[I 2022-03-27 18:15:05,022] Trial 20 finished with value: 0.38680737289053396 and parameters: {'regressor': 'LightGBM', 'max_depth': 14, 'max_features': 12}. Best is trial 18 with value: 0.3882812159412718.
[I 2022-03-27 18:15:06,121] Trial 21 finished with value: 0.38886466722079166 and parameters: {'regressor': 'LightGBM', 'max_depth': 11, 'max_features': 11}. Best is trial 21 with value: 0.38886466722079166.
[I 2022-03-27 18:15:07,224] Trial 22 finished with value: 0.38886466722079166 and parameters: {'regressor': 'LightGBM', 'max_depth': 11, 'max_features': 11}. Best is trial 21 with value: 0.38886466722079166.
[I 2022-03-27 18:15:08,323] Trial 23 finished with value: 0.38886466722079166 and parameters: {'regressor': 'LightGBM', 'max_depth': 11, 'max_features': 14}. Best is trial 21 with value: 0.38886466722079166.
[I 2022-03-27 18:15:09,426] Trial 24 finished with value: 0.38886466722079166 and parameters: {'regressor': 'LightGBM', 'max_depth': 11, 'max_features': 15}. Best is trial 21 with value: 0.38886466722079166.
[I 2022-03-27 18:15:10,535] Trial 25 finished with value: 0.38680737289053396 and parameters: {'regressor': 'LightGBM', 'max_depth': 14, 'max_features': 16}. Best is trial 21 with value: 0.38886466722079166.
[I 2022-03-27 18:15:11,640] Trial 26 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:12,759] Trial 27 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:13,892] Trial 28 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 15}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:25,924] Trial 29 finished with value: 0.348097286333011 and parameters: {'regressor': 'RandomForest', 'max_depth': 9, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:27,035] Trial 30 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:28,123] Trial 31 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:29,228] Trial 32 finished with value: 0.38780396438906567 and parameters: {'regressor': 'LightGBM', 'max_depth': 8, 'max_features': 15}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:30,336] Trial 33 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 13}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:31,475] Trial 34 finished with value: 0.38780396438906567 and parameters: {'regressor': 'LightGBM', 'max_depth': 8, 'max_features': 13}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:32,571] Trial 35 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 15}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:33,577] Trial 36 finished with value: 0.38634580523343964 and parameters: {'regressor': 'LightGBM', 'max_depth': 13, 'max_features': 13}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:34,696] Trial 37 finished with value: 0.3858121530268348 and parameters: {'regressor': 'LightGBM', 'max_depth': 9, 'max_features': 12}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:52,424] Trial 38 finished with value: 0.3551982808498321 and parameters: {'regressor': 'RandomForest', 'max_depth': 13, 'max_features': 16}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:53,534] Trial 39 finished with value: 0.38780396438906567 and parameters: {'regressor': 'LightGBM', 'max_depth': 8, 'max_features': 15}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:54,663] Trial 40 finished with value: 0.38671654769148894 and parameters: {'regressor': 'LightGBM', 'max_depth': 7, 'max_features': 13}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:55,760] Trial 41 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:56,877] Trial 42 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:57,963] Trial 43 finished with value: 0.3882812159412718 and parameters: {'regressor': 'LightGBM', 'max_depth': 12, 'max_features': 12}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:15:59,077] Trial 44 finished with value: 0.3858121530268348 and parameters: {'regressor': 'LightGBM', 'max_depth': 9, 'max_features': 16}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:16:21,168] Trial 45 finished with value: 0.32427931044253355 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 11, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:16:22,261] Trial 46 finished with value: 0.3882812159412718 and parameters: {'regressor': 'LightGBM', 'max_depth': 12, 'max_features': 15}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:16:34,436] Trial 47 finished with value: 0.35398758463301433 and parameters: {'regressor': 'RandomForest', 'max_depth': 10, 'max_features': 13}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:16:45,784] Trial 48 finished with value: 0.354964505140277 and parameters: {'regressor': 'XGBoost', 'max_depth': 9, 'max_features': 11}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:16:46,878] Trial 49 finished with value: 0.3837451601243402 and parameters: {'regressor': 'LightGBM', 'max_depth': 6, 'max_features': 15}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:17:08,929] Trial 50 finished with value: 0.32427931044253355 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 11, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:17:10,040] Trial 51 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 16}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:17:11,142] Trial 52 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 16}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:17:12,262] Trial 53 finished with value: 0.3858121530268348 and parameters: {'regressor': 'LightGBM', 'max_depth': 9, 'max_features': 13}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:17:13,390] Trial 54 finished with value: 0.38780396438906567 and parameters: {'regressor': 'LightGBM', 'max_depth': 8, 'max_features': 8}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:17:14,502] Trial 55 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 15}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:17:22,803] Trial 56 finished with value: 0.3722141260506455 and parameters: {'regressor': 'XGBoost', 'max_depth': 7, 'max_features': 16}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:17:23,908] Trial 57 finished with value: 0.3882812159412718 and parameters: {'regressor': 'LightGBM', 'max_depth': 12, 'max_features': 15}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:17:25,020] Trial 58 finished with value: 0.38886466722079166 and parameters: {'regressor': 'LightGBM', 'max_depth': 11, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:17:42,525] Trial 59 finished with value: 0.3411443951715967 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 10, 'max_features': 12}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:17:43,676] Trial 60 finished with value: 0.3858121530268348 and parameters: {'regressor': 'LightGBM', 'max_depth': 9, 'max_features': 16}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:17:44,790] Trial 61 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:17:45,900] Trial 62 finished with value: 0.38886466722079166 and parameters: {'regressor': 'LightGBM', 'max_depth': 11, 'max_features': 16}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:17:47,043] Trial 63 finished with value: 0.38780396438906567 and parameters: {'regressor': 'LightGBM', 'max_depth': 8, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:17:48,165] Trial 64 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 13}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:18:00,266] Trial 65 finished with value: 0.36081943488243695 and parameters: {'regressor': 'RandomForest', 'max_depth': 12, 'max_features': 11}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:18:01,409] Trial 66 finished with value: 0.3858121530268348 and parameters: {'regressor': 'LightGBM', 'max_depth': 9, 'max_features': 15}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:18:02,528] Trial 67 finished with value: 0.38886466722079166 and parameters: {'regressor': 'LightGBM', 'max_depth': 11, 'max_features': 16}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:18:17,607] Trial 68 finished with value: 0.3297498389624873 and parameters: {'regressor': 'XGBoost', 'max_depth': 11, 'max_features': 13}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:18:18,751] Trial 69 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 12}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:18:19,880] Trial 70 finished with value: 0.3858121530268348 and parameters: {'regressor': 'LightGBM', 'max_depth': 9, 'max_features': 12}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:18:20,997] Trial 71 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 15}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:18:22,113] Trial 72 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 15}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:18:23,238] Trial 73 finished with value: 0.3858121530268348 and parameters: {'regressor': 'LightGBM', 'max_depth': 9, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:18:24,338] Trial 74 finished with value: 0.38886466722079166 and parameters: {'regressor': 'LightGBM', 'max_depth': 11, 'max_features': 15}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:18:25,470] Trial 75 finished with value: 0.38671654769148894 and parameters: {'regressor': 'LightGBM', 'max_depth': 7, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:18:26,598] Trial 76 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 13}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:18:27,714] Trial 77 finished with value: 0.38886466722079166 and parameters: {'regressor': 'LightGBM', 'max_depth': 11, 'max_features': 16}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:18:40,830] Trial 78 finished with value: 0.3523125747859723 and parameters: {'regressor': 'RandomForest', 'max_depth': 10, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:18:56,976] Trial 79 finished with value: 0.3623901838280303 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 8, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:18:58,107] Trial 80 finished with value: 0.3858121530268348 and parameters: {'regressor': 'LightGBM', 'max_depth': 9, 'max_features': 12}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:18:59,243] Trial 81 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 13}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:19:00,384] Trial 82 finished with value: 0.3858121530268348 and parameters: {'regressor': 'LightGBM', 'max_depth': 9, 'max_features': 15}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:19:01,496] Trial 83 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 13}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:19:02,615] Trial 84 finished with value: 0.38886466722079166 and parameters: {'regressor': 'LightGBM', 'max_depth': 11, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:19:03,730] Trial 85 finished with value: 0.38886466722079166 and parameters: {'regressor': 'LightGBM', 'max_depth': 11, 'max_features': 15}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:19:04,519] Trial 86 finished with value: 0.359339894831263 and parameters: {'regressor': 'LightGBM', 'max_depth': 3, 'max_features': 16}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:19:22,047] Trial 87 finished with value: 0.31814052509798746 and parameters: {'regressor': 'XGBoost', 'max_depth': 12, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:19:23,159] Trial 88 finished with value: 0.38662046933653405 and parameters: {'regressor': 'LightGBM', 'max_depth': 16, 'max_features': 15}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:19:24,306] Trial 89 finished with value: 0.38780396438906567 and parameters: {'regressor': 'LightGBM', 'max_depth': 8, 'max_features': 14}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:19:25,419] Trial 90 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 6}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:19:26,537] Trial 91 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 6}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:19:27,663] Trial 92 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 7}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:19:28,800] Trial 93 finished with value: 0.3858121530268348 and parameters: {'regressor': 'LightGBM', 'max_depth': 9, 'max_features': 6}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:19:29,912] Trial 94 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 13}. Best is trial 26 with value: 0.3892534050390631.
[I 2022-03-27 18:19:31,061] Trial 95 finished with value: 0.3892534050390631 and parameters: {'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 13}. Best is trial 26 with value: 0.3892534050390631.

FrozenTrial(number=26, values=[0.3892534050390631], datetime_start=datetime.datetime(2022, 3, 27, 18, 15, 10, 539185), datetime_complete=datetime.datetime(2022, 3, 27, 18, 15, 11, 639600), params={'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 14}, distributions={'regressor': CategoricalDistribution(choices=('GradientBoosting', 'XGBoost', 'LightGBM', 'RandomForest')), 'max_depth': IntUniformDistribution(high=16, low=2, step=1), 'max_features': IntUniformDistribution(high=16, low=2, step=1)}, user_attrs={}, system_attrs={}, intermediate_values={}, trial_id=26, state=TrialState.COMPLETE, value=None)

In [14]:
print(study.best_params)

{'regressor': 'LightGBM', 'max_depth': 10, 'max_features': 14}

In [15]:
import lightgbm as lgb
lgb_model = lgb.LGBMClassifier(random_state=17,max_depth=10,max_features=14)
lgb_model.fit(X_train, y_train)
# make predictions for test data
print(accuracy_score(y_test, lgb_model.predict(X_test)))

0.905511811023622

For Q3 and Q4 ,use the following data.

In [17]:
dr=pd.read_csv('https://raw.githubusercontent.com/ogut77/DataScience/main/data/diamond.csv')
dr

,Carat Weight,Cut,Color,Clarity,Polish,Symmetry,Report,Price
0,1.10,Ideal,H,SI1,VG,EX,GIA,5169
1,0.83,Ideal,H,VS1,ID,ID,AGSL,3470
2,0.85,Ideal,H,SI1,EX,EX,GIA,3183
3,0.91,Ideal,E,SI1,VG,VG,GIA,4370
4,0.83,Ideal,G,SI1,EX,EX,GIA,3171
...,...,...,...,...,...,...,...,...
5995,1.03,Ideal,D,SI1,EX,EX,GIA,6250
5996,1.00,Very Good,D,SI1,VG,VG,GIA,5328
5997,1.02,Ideal,D,SI1,EX,EX,GIA,6157
5998,1.27,Signature-Ideal,G,VS1,EX,EX,GIA,11206
5999,2.19,Ideal,E,VS1,EX,EX,GIA,30507

In [18]:
dr=pd.read_csv('https://raw.githubusercontent.com/ogut77/DataScience/main/data/diamond.csv')
dr

,Carat Weight,Cut,Color,Clarity,Polish,Symmetry,Report,Price
0,1.10,Ideal,H,SI1,VG,EX,GIA,5169
1,0.83,Ideal,H,VS1,ID,ID,AGSL,3470
2,0.85,Ideal,H,SI1,EX,EX,GIA,3183
3,0.91,Ideal,E,SI1,VG,VG,GIA,4370
4,0.83,Ideal,G,SI1,EX,EX,GIA,3171
...,...,...,...,...,...,...,...,...
5995,1.03,Ideal,D,SI1,EX,EX,GIA,6250
5996,1.00,Very Good,D,SI1,VG,VG,GIA,5328
5997,1.02,Ideal,D,SI1,EX,EX,GIA,6157
5998,1.27,Signature-Ideal,G,VS1,EX,EX,GIA,11206
5999,2.19,Ideal,E,VS1,EX,EX,GIA,30507

In [19]:
def Encoder(df):
          from sklearn import preprocessing
          columnsToEncode = list(df.select_dtypes(include=['category','object']))
          le = preprocessing.LabelEncoder()
          for feature in columnsToEncode:
              try:
                  df[feature] = le.fit_transform(df[feature])
              except:
                  print('Error encoding '+feature)
          return df

In [20]:
dr=Encoder(dr)
dr

      Carat Weight  Cut  Color  Clarity  Polish  Symmetry  Report  Price
0             1.10    2      4        2       3         0       1   5169
1             0.83    2      4        3       2         2       0   3470
2             0.85    2      4        2       0         0       1   3183
3             0.91    2      1        2       3         3       1   4370
4             0.83    2      3        2       0         0       1   3171
...            ...  ...    ...      ...     ...       ...     ...    ...
5995          1.03    2      0        2       0         0       1   6250
5996          1.00    4      0        2       3         3       1   5328
5997          1.02    2      0        2       0         0       1   6157
5998          1.27    3      3        3       0         0       1  11206
5999          2.19    2      1        3       0         0       1  30507

[6000 rows x 8 columns]

In [21]:
y = dr['Price'] #Output
X = dr.drop('Price',axis=1)
X

      Carat Weight  Cut  Color  Clarity  Polish  Symmetry  Report
0             1.10    2      4        2       3         0       1
1             0.83    2      4        3       2         2       0
2             0.85    2      4        2       0         0       1
3             0.91    2      1        2       3         3       1
4             0.83    2      3        2       0         0       1
...            ...  ...    ...      ...     ...       ...     ...
5995          1.03    2      0        2       0         0       1
5996          1.00    4      0        2       3         3       1
5997          1.02    2      0        2       0         0       1
5998          1.27    3      3        3       0         0       1
5999          2.19    2      1        3       0         0       1

[6000 rows x 7 columns]

In [22]:
from sklearn.model_selection import  train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=17)

Q3)Using Linear Regression,Decison Tree Random Forest,XGBoost, Light GBM and Gradient Boosting Classifier with default parameters (no parameter specifications except random_state) calculate R2 statistics on test data. Which method gives the best accuracy on test data

In [25]:
def evalmetric(y,ypred):
 import numpy as np
 e = y - ypred 
 mse_f = np.mean(e**2)
 rmse_f = np.sqrt(mse_f)
 mae_f = np.mean(abs(e))
 mape_f = 100*np.mean(abs(e/y))
 r2_f = 1-(sum(e**2)/sum((y-np.mean(y))**2))
 print("MSE:", mse_f)
 print("RMSE:", rmse_f)
 print("MAE:",mae_f)
 print("MAPE:",mape_f)
 print("R-Squared:", r2_f)

In [26]:
#Question3
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(random_state=17)
dtr.fit(X_train,y_train)
print('Test Data')
y_pred2 = dtr.predict(X_test)
evalmetric(y_test,y_pred2)

Test Data
MSE: 4222331.073863685
RMSE: 2054.83115458757
MAE: 1016.694373015873
MAPE: 7.833274374700561
R-Squared: 0.9592329752745201

In [27]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(random_state=17)
rfr.fit(X_train,y_train)
print('Test Data')
y_pred2 = rfr.predict(X_test)
evalmetric(y_test,y_pred2)

Test Data
MSE: 2074962.900565573
RMSE: 1440.4731516295515
MAE: 778.3143303628775
MAPE: 6.220426902140035
R-Squared: 0.9799660276771226

In [28]:
from sklearn.ensemble import GradientBoostingRegressor
from time import time

gbr = GradientBoostingRegressor(random_state=17)
gbr.fit(X_train, y_train)
print('Test Data')
y_pred2 = gbr.predict(X_test)
evalmetric(y_test,y_pred2)

Test Data
MSE: 2702865.535065862
RMSE: 1644.0393958375396
MAE: 878.4993508475277
MAPE: 7.394144503096002
R-Squared: 0.9739035655494326

In [29]:
from xgboost import XGBRegressor
xgr = XGBRegressor(random_state=17)
xgr.fit(X_train, y_train)
print('Test Data')
y_pred2 = xgr.predict(X_test)
evalmetric(y_test,y_pred2)

[18:24:42] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
Test Data
MSE: 2822838.991584785
RMSE: 1680.1306471774108
MAE: 881.3905965169271
MAPE: 7.3386749783130245
R-Squared: 0.9727452099437854

In [30]:
from time import time
import lightgbm as lgb
t0 = time()
lgr = lgb.LGBMRegressor(random_state=17)
lgr.fit(X_train, y_train)
print('Test Data')
y_pred2 = lgr.predict(X_test)
evalmetric(y_test,y_pred2)

Test Data
MSE: 1940840.8294753155
RMSE: 1393.1406352107153
MAE: 701.0864858904304
MAPE: 5.433753614630323
R-Squared: 0.9812609895578275

In [31]:
import sklearn.linear_model as skl_lm
regr = skl_lm.LinearRegression()
regr.fit(X_train,y_train)
print('Test Data')
y_pred2 = regr.predict(X_test)
evalmetric(y_test,y_pred2)

Test Data
MSE: 18292450.049325157
RMSE: 4276.967389322153
MAE: 2701.997276609754
MAPE: 30.68442425409791
R-Squared: 0.8233845829696962

Q4) Using optuna hyperparmeter optimization technique (100 trial) with Random Forest,XGBoost, Light GBM and Gradient Boosting Regressor

a)find best methods with parameters using Cross validation (CV=3) technique for the range of parameters below. What are the best parameters for the method with highest cross validation R2?

"max_depth": range(2, 7), "max_features": range(2, 7)

b)Evaluate the performance of the method with highest cross validation R2 on test data. What is the R2 value?

In [33]:
import optuna

import sklearn.datasets
import sklearn.ensemble
import sklearn.model_selection
import sklearn.svm


# FYI: Objective functions can take additional arguments
# (https://optuna.readthedocs.io/en/stable/faq.html#objective-func-additional-args).
def objective(trial):
    x, y = X_train,y_train

    regressor_name = trial.suggest_categorical("regressor", ["GradientBoosting", "XGBoost","LightGBM","RandomForest"])
    if regressor_name == "GradientBoosting":
         max_depth = trial.suggest_int("max_depth", 2,7)
         max_features = trial.suggest_int("max_features", 2,7)
         regressor_obj = sklearn.ensemble.GradientBoostingRegressor(random_state=17,  max_depth=max_depth, max_features=max_features )
    
    elif regressor_name == "XGBoost":
         from xgboost import XGBRegressor
         max_depth = trial.suggest_int("max_depth", 2,7)
         max_features = trial.suggest_int("max_features", 2,7)
         regressor_obj = XGBRegressor(random_state=17,  max_depth=max_depth, max_features=max_features )
        
         

    elif regressor_name == "LightGBM":
         import lightgbm as lgb
         max_depth = trial.suggest_int("max_depth", 2,7)
         max_features = trial.suggest_int("max_features", 2,7)
         regressor_obj = lgb.LGBMRegressor(random_state=17,  max_depth=max_depth, max_features=max_features )
        
    else:
         max_depth = trial.suggest_int("max_depth", 2,7)
         max_features = trial.suggest_int("max_features", 2,7)
         regressor_obj = sklearn.ensemble.RandomForestRegressor(random_state=17,  max_depth=max_depth, max_features=max_features )

     

    r2=sklearn.model_selection.cross_val_score(regressor_obj, x, y, n_jobs=-1, cv=3).mean()
   
    return r2


if __name__ == "__main__":
    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=100)
    print(study.best_trial)

[I 2022-03-27 18:26:15,758] A new study created in memory with name: no-name-b68fd85f-7705-44de-a7a2-faed685c1807
[I 2022-03-27 18:26:18,381] Trial 0 finished with value: 0.7739509743309535 and parameters: {'regressor': 'RandomForest', 'max_depth': 2, 'max_features': 5}. Best is trial 0 with value: 0.7739509743309535.
[I 2022-03-27 18:26:18,839] Trial 1 finished with value: 0.9783683994728235 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 3, 'max_features': 6}. Best is trial 1 with value: 0.9783683994728235.
[I 2022-03-27 18:26:19,400] Trial 2 finished with value: 0.9851666718949561 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 5}. Best is trial 2 with value: 0.9851666718949561.
[I 2022-03-27 18:26:20,161] Trial 3 finished with value: 0.9840024346566438 and parameters: {'regressor': 'XGBoost', 'max_depth': 7, 'max_features': 5}. Best is trial 2 with value: 0.9851666718949561.
[I 2022-03-27 18:26:20,436] Trial 4 finished with value: 0.9548589700649653 and parameters: {'regressor': 'XGBoost', 'max_depth': 2, 'max_features': 4}. Best is trial 2 with value: 0.9851666718949561.
[I 2022-03-27 18:26:20,783] Trial 5 finished with value: 0.9771377197784242 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 2}. Best is trial 2 with value: 0.9851666718949561.
[I 2022-03-27 18:26:21,430] Trial 6 finished with value: 0.9845567951821383 and parameters: {'regressor': 'XGBoost', 'max_depth': 6, 'max_features': 2}. Best is trial 2 with value: 0.9851666718949561.
[I 2022-03-27 18:26:21,827] Trial 7 finished with value: 0.9758296442252078 and parameters: {'regressor': 'LightGBM', 'max_depth': 7, 'max_features': 6}. Best is trial 2 with value: 0.9851666718949561.
[I 2022-03-27 18:26:22,111] Trial 8 finished with value: 0.9498980755871994 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 2, 'max_features': 4}. Best is trial 2 with value: 0.9851666718949561.
[I 2022-03-27 18:26:22,354] Trial 9 finished with value: 0.9460197158478415 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 2, 'max_features': 3}. Best is trial 2 with value: 0.9851666718949561.
[I 2022-03-27 18:26:22,506] Trial 10 finished with value: 0.9761140473772666 and parameters: {'regressor': 'LightGBM', 'max_depth': 4, 'max_features': 7}. Best is trial 2 with value: 0.9851666718949561.
[I 2022-03-27 18:26:23,045] Trial 11 finished with value: 0.9842502916631269 and parameters: {'regressor': 'XGBoost', 'max_depth': 5, 'max_features': 2}. Best is trial 2 with value: 0.9851666718949561.
[I 2022-03-27 18:26:23,666] Trial 12 finished with value: 0.9375844290578602 and parameters: {'regressor': 'RandomForest', 'max_depth': 6, 'max_features': 3}. Best is trial 2 with value: 0.9851666718949561.
[I 2022-03-27 18:26:24,310] Trial 13 finished with value: 0.9845567951821383 and parameters: {'regressor': 'XGBoost', 'max_depth': 6, 'max_features': 3}. Best is trial 2 with value: 0.9851666718949561.
[I 2022-03-27 18:26:24,740] Trial 14 finished with value: 0.9837177913038949 and parameters: {'regressor': 'XGBoost', 'max_depth': 4, 'max_features': 6}. Best is trial 2 with value: 0.9851666718949561.
[I 2022-03-27 18:26:25,310] Trial 15 finished with value: 0.9851482213099071 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 4}. Best is trial 2 with value: 0.9851666718949561.
[I 2022-03-27 18:26:25,869] Trial 16 finished with value: 0.9851666718949561 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 5}. Best is trial 2 with value: 0.9851666718949561.
[I 2022-03-27 18:26:26,577] Trial 17 finished with value: 0.9856357090076635 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 17 with value: 0.9856357090076635.
[I 2022-03-27 18:26:27,182] Trial 18 finished with value: 0.985430200504429 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 17 with value: 0.9856357090076635.
[I 2022-03-27 18:26:27,663] Trial 19 finished with value: 0.9793352911668259 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 3, 'max_features': 7}. Best is trial 17 with value: 0.9856357090076635.
[I 2022-03-27 18:26:28,345] Trial 20 finished with value: 0.9073338809892725 and parameters: {'regressor': 'RandomForest', 'max_depth': 4, 'max_features': 7}. Best is trial 17 with value: 0.9856357090076635.
[I 2022-03-27 18:26:28,965] Trial 21 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:29,453] Trial 22 finished with value: 0.9793352911668259 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 3, 'max_features': 7}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:29,978] Trial 23 finished with value: 0.985691766023269 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:30,154] Trial 24 finished with value: 0.9765224083258769 and parameters: {'regressor': 'LightGBM', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:30,693] Trial 25 finished with value: 0.985691766023269 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:31,138] Trial 26 finished with value: 0.9783683994728235 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 3, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:31,668] Trial 27 finished with value: 0.985691766023269 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:32,143] Trial 28 finished with value: 0.9852245763533835 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 5}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:32,723] Trial 29 finished with value: 0.8660534697962478 and parameters: {'regressor': 'RandomForest', 'max_depth': 3, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:32,867] Trial 30 finished with value: 0.9761140473772666 and parameters: {'regressor': 'LightGBM', 'max_depth': 4, 'max_features': 5}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:33,411] Trial 31 finished with value: 0.985691766023269 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:33,945] Trial 32 finished with value: 0.985691766023269 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:34,414] Trial 33 finished with value: 0.9783683994728235 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 3, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:34,978] Trial 34 finished with value: 0.9851666718949561 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 5}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:35,385] Trial 35 finished with value: 0.978584587565372 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 3, 'max_features': 5}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:36,012] Trial 36 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:36,766] Trial 37 finished with value: 0.9389705102712522 and parameters: {'regressor': 'RandomForest', 'max_depth': 5, 'max_features': 7}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:37,500] Trial 38 finished with value: 0.9855384347911574 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:38,059] Trial 39 finished with value: 0.9851666718949561 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 5}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:38,789] Trial 40 finished with value: 0.9855384347911574 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:39,328] Trial 41 finished with value: 0.985691766023269 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:39,943] Trial 42 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:40,577] Trial 43 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:40,742] Trial 44 finished with value: 0.9765224083258769 and parameters: {'regressor': 'LightGBM', 'max_depth': 5, 'max_features': 7}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:41,389] Trial 45 finished with value: 0.9853949933706203 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 5}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:41,924] Trial 46 finished with value: 0.9842502916631269 and parameters: {'regressor': 'XGBoost', 'max_depth': 5, 'max_features': 4}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:42,554] Trial 47 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:43,483] Trial 48 finished with value: 0.9845900585712223 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 7, 'max_features': 7}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:44,200] Trial 49 finished with value: 0.9634604096785503 and parameters: {'regressor': 'RandomForest', 'max_depth': 6, 'max_features': 5}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:44,834] Trial 50 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:45,461] Trial 51 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:46,084] Trial 52 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:46,717] Trial 53 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:47,246] Trial 54 finished with value: 0.9842502916631269 and parameters: {'regressor': 'XGBoost', 'max_depth': 5, 'max_features': 7}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:47,894] Trial 55 finished with value: 0.9853949933706203 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 5}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:48,516] Trial 56 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:48,678] Trial 57 finished with value: 0.9765224083258769 and parameters: {'regressor': 'LightGBM', 'max_depth': 5, 'max_features': 7}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:49,392] Trial 58 finished with value: 0.9855384347911574 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:50,012] Trial 59 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:50,705] Trial 60 finished with value: 0.9856357090076635 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:51,326] Trial 61 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:51,951] Trial 62 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:52,572] Trial 63 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:53,281] Trial 64 finished with value: 0.9855384347911574 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:53,811] Trial 65 finished with value: 0.9842502916631269 and parameters: {'regressor': 'XGBoost', 'max_depth': 5, 'max_features': 5}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:54,439] Trial 66 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:54,796] Trial 67 finished with value: 0.9771377197784242 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 2}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:55,371] Trial 68 finished with value: 0.9190596935225731 and parameters: {'regressor': 'RandomForest', 'max_depth': 5, 'max_features': 3}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:56,096] Trial 69 finished with value: 0.9855384347911574 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:56,239] Trial 70 finished with value: 0.9761140473772666 and parameters: {'regressor': 'LightGBM', 'max_depth': 4, 'max_features': 7}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:56,872] Trial 71 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:57,492] Trial 72 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:58,125] Trial 73 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:58,751] Trial 74 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:59,307] Trial 75 finished with value: 0.9851666718949561 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 5}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:26:59,832] Trial 76 finished with value: 0.985691766023269 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:27:00,446] Trial 77 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:27:01,242] Trial 78 finished with value: 0.9844596675452194 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 7}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:27:01,519] Trial 79 finished with value: 0.9498980755871994 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 2, 'max_features': 4}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:27:02,140] Trial 80 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:27:02,765] Trial 81 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:27:03,379] Trial 82 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:27:04,001] Trial 83 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:27:04,619] Trial 84 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:27:05,158] Trial 85 finished with value: 0.9842502916631269 and parameters: {'regressor': 'XGBoost', 'max_depth': 5, 'max_features': 5}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:27:05,783] Trial 86 finished with value: 0.9153488693549434 and parameters: {'regressor': 'RandomForest', 'max_depth': 4, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:27:06,414] Trial 87 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:27:07,044] Trial 88 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:27:07,866] Trial 89 finished with value: 0.9844596675452194 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 7}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:27:08,011] Trial 90 finished with value: 0.9761140473772666 and parameters: {'regressor': 'LightGBM', 'max_depth': 4, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:27:09,045] Trial 91 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:27:09,778] Trial 92 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.
[I 2022-03-27 18:27:10,412] Trial 93 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 21 with value: 0.9861873336374272.

FrozenTrial(number=21, values=[0.9861873336374272], datetime_start=datetime.datetime(2022, 3, 27, 18, 26, 28, 347644), datetime_complete=datetime.datetime(2022, 3, 27, 18, 26, 28, 965027), params={'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}, distributions={'regressor': CategoricalDistribution(choices=('GradientBoosting', 'XGBoost', 'LightGBM', 'RandomForest')), 'max_depth': IntUniformDistribution(high=7, low=2, step=1), 'max_features': IntUniformDistribution(high=7, low=2, step=1)}, user_attrs={}, system_attrs={}, intermediate_values={}, trial_id=21, state=TrialState.COMPLETE, value=None)

In [34]:
print(study.best_params)

{'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=17)
from sklearn.ensemble import GradientBoostingRegressor
from time import time

gbr = GradientBoostingRegressor(random_state=17,max_depth= 5,max_features= 6)
gbr.fit(X_train,y_train)
print('Test Data')
y_pred2 = gbr.predict(X_test)
evalmetric(y_test,y_pred2)

Test Data
MSE: 1542353.8550284477
RMSE: 1241.915397693598
MAE: 659.2526559755419
MAPE: 5.307389159446252
R-Squared: 0.985108420764872